name: floor_plan_builder
description: A Flutter package for building floor plans with tables.
version: 0.0.1
homepage: https://github.com/vishalxtyagi/floor_plan_builder

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/table_shapes/